all: Prinsimp-introduction.pdf

clean:
	rm -f *.tex *.bbl *.blg *.aux *.out *.log *.spl *tikzDictionary

Prinsimp-introduction.pdf:
	# test -f Prinsimp-introduction-real.pdf && mv Prinsimp-introduction-real.pdf Prinsimp-introduction.pdf
	mv Prinsimp-introduction-real.pdf Prinsimp-introduction.pdf || echo
